import type {
  Contact,
  Conversation,
  Message,
  Order,
  AIAgent,
} from '@/types';

const DEMO_TEAM_ID = 'demo-team';

export const demoContacts: Contact[] = [
  {
    id: 'c1',
    teamId: DEMO_TEAM_ID,
    name: 'María García',
    phone: '+52 55 1234 5678',
    email: 'maria@email.com',
    platform: 'whatsapp',
    platformId: '5215512345678',
    tags: ['cliente-vip', 'recurrente'],
    notes: 'Cliente frecuente, prefiere entregas por la tarde.',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-06T14:30:00Z',
    lastMessageAt: '2026-03-06T14:30:00Z',
  },
  {
    id: 'c2',
    teamId: DEMO_TEAM_ID,
    name: 'Carlos López',
    phone: '+52 33 9876 5432',
    platform: 'whatsapp',
    platformId: '5213398765432',
    tags: ['nuevo'],
    notes: '',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-06T12:15:00Z',
    lastMessageAt: '2026-03-06T12:15:00Z',
  },
  {
    id: 'c3',
    teamId: DEMO_TEAM_ID,
    name: 'Ana Martínez',
    phone: '+52 81 5555 1234',
    platform: 'messenger',
    platformId: 'ana.mtz.fb',
    tags: ['prospecto'],
    notes: 'Interesada en productos de skincare.',
    createdAt: '2026-03-03T16:00:00Z',
    updatedAt: '2026-03-05T20:45:00Z',
    lastMessageAt: '2026-03-05T20:45:00Z',
  },
  {
    id: 'c4',
    teamId: DEMO_TEAM_ID,
    name: 'Roberto Sánchez',
    platform: 'instagram',
    platformId: 'rob_sanchez_ig',
    tags: ['influencer'],
    notes: 'Colaboración pendiente.',
    createdAt: '2026-02-20T12:00:00Z',
    updatedAt: '2026-03-04T18:00:00Z',
    lastMessageAt: '2026-03-04T18:00:00Z',
  },
  {
    id: 'c5',
    teamId: DEMO_TEAM_ID,
    name: 'Laura Fernández',
    phone: '+52 55 7777 8888',
    email: 'laura.f@empresa.com',
    platform: 'whatsapp',
    platformId: '5215577778888',
    tags: ['mayorista'],
    notes: 'Compras al mayoreo, pide factura.',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-03-06T10:00:00Z',
    lastMessageAt: '2026-03-06T10:00:00Z',
  },
];

export const demoConversations: Conversation[] = [
  {
    id: 'conv1',
    teamId: DEMO_TEAM_ID,
    contactId: 'c1',
    contact: demoContacts[0],
    platform: 'whatsapp',
    assignedTo: 'agent1',
    status: 'open',
    aiEnabled: false,
    unreadCount: 2,
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-06T14:30:00Z',
    lastMessage: {
      id: 'm3',
      conversationId: 'conv1',
      contactId: 'c1',
      teamId: DEMO_TEAM_ID,
      direction: 'inbound',
      platform: 'whatsapp',
      content: 'Hola, ¿ya está listo mi pedido? 📦',
      messageType: 'text',
      status: 'delivered',
      isAiGenerated: false,
      createdAt: '2026-03-06T14:30:00Z',
    },
  },
  {
    id: 'conv2',
    teamId: DEMO_TEAM_ID,
    contactId: 'c2',
    contact: demoContacts[1],
    platform: 'whatsapp',
    status: 'open',
    aiEnabled: true,
    unreadCount: 0,
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-06T12:15:00Z',
    lastMessage: {
      id: 'm6',
      conversationId: 'conv2',
      contactId: 'c2',
      teamId: DEMO_TEAM_ID,
      direction: 'outbound',
      platform: 'whatsapp',
      content: '¡Claro! Te mando el catálogo completo.',
      messageType: 'text',
      status: 'read',
      isAiGenerated: true,
      createdAt: '2026-03-06T12:15:00Z',
    },
  },
  {
    id: 'conv3',
    teamId: DEMO_TEAM_ID,
    contactId: 'c3',
    contact: demoContacts[2],
    platform: 'messenger',
    status: 'pending',
    aiEnabled: false,
    unreadCount: 1,
    createdAt: '2026-03-03T16:00:00Z',
    updatedAt: '2026-03-05T20:45:00Z',
    lastMessage: {
      id: 'm9',
      conversationId: 'conv3',
      contactId: 'c3',
      teamId: DEMO_TEAM_ID,
      direction: 'inbound',
      platform: 'messenger',
      content: '¿Tienen envíos a Monterrey?',
      messageType: 'text',
      status: 'delivered',
      isAiGenerated: false,
      createdAt: '2026-03-05T20:45:00Z',
    },
  },
  {
    id: 'conv4',
    teamId: DEMO_TEAM_ID,
    contactId: 'c4',
    contact: demoContacts[3],
    platform: 'instagram',
    status: 'closed',
    aiEnabled: false,
    unreadCount: 0,
    createdAt: '2026-02-20T12:00:00Z',
    updatedAt: '2026-03-04T18:00:00Z',
    lastMessage: {
      id: 'm12',
      conversationId: 'conv4',
      contactId: 'c4',
      teamId: DEMO_TEAM_ID,
      direction: 'outbound',
      platform: 'instagram',
      content: 'Perfecto, queda confirmada la colaboración.',
      messageType: 'text',
      status: 'read',
      isAiGenerated: false,
      createdAt: '2026-03-04T18:00:00Z',
    },
  },
  {
    id: 'conv5',
    teamId: DEMO_TEAM_ID,
    contactId: 'c5',
    contact: demoContacts[4],
    platform: 'whatsapp',
    status: 'open',
    aiEnabled: false,
    unreadCount: 3,
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-03-06T10:00:00Z',
    lastMessage: {
      id: 'm15',
      conversationId: 'conv5',
      contactId: 'c5',
      teamId: DEMO_TEAM_ID,
      direction: 'inbound',
      platform: 'whatsapp',
      content: 'Necesito 50 unidades del SKU-2024, ¿tienen stock?',
      messageType: 'text',
      status: 'delivered',
      isAiGenerated: false,
      createdAt: '2026-03-06T10:00:00Z',
    },
  },
];

export const demoMessages: Record<string, Message[]> = {
  conv1: [
    {
      id: 'm1', conversationId: 'conv1', contactId: 'c1', teamId: DEMO_TEAM_ID,
      direction: 'inbound', platform: 'whatsapp', content: 'Hola, quiero hacer un pedido.',
      messageType: 'text', status: 'read', isAiGenerated: false, createdAt: '2026-03-06T14:00:00Z',
    },
    {
      id: 'm2', conversationId: 'conv1', contactId: 'c1', teamId: DEMO_TEAM_ID,
      direction: 'outbound', platform: 'whatsapp', content: '¡Hola María! Con gusto te ayudo. ¿Qué productos te interesan?',
      messageType: 'text', status: 'read', sentBy: 'agent1', isAiGenerated: false, createdAt: '2026-03-06T14:05:00Z',
    },
    {
      id: 'm3', conversationId: 'conv1', contactId: 'c1', teamId: DEMO_TEAM_ID,
      direction: 'inbound', platform: 'whatsapp', content: 'Hola, ¿ya está listo mi pedido? 📦',
      messageType: 'text', status: 'delivered', isAiGenerated: false, createdAt: '2026-03-06T14:30:00Z',
    },
  ],
  conv2: [
    {
      id: 'm4', conversationId: 'conv2', contactId: 'c2', teamId: DEMO_TEAM_ID,
      direction: 'inbound', platform: 'whatsapp', content: 'Buenas, ¿qué productos manejan?',
      messageType: 'text', status: 'read', isAiGenerated: false, createdAt: '2026-03-06T12:00:00Z',
    },
    {
      id: 'm5', conversationId: 'conv2', contactId: 'c2', teamId: DEMO_TEAM_ID,
      direction: 'outbound', platform: 'whatsapp', content: '¡Hola Carlos! Manejamos una gran variedad de productos. ¿Buscas algo en específico?',
      messageType: 'text', status: 'read', isAiGenerated: true, createdAt: '2026-03-06T12:01:00Z',
    },
    {
      id: 'm6', conversationId: 'conv2', contactId: 'c2', teamId: DEMO_TEAM_ID,
      direction: 'outbound', platform: 'whatsapp', content: '¡Claro! Te mando el catálogo completo.',
      messageType: 'text', status: 'read', isAiGenerated: true, createdAt: '2026-03-06T12:15:00Z',
    },
  ],
  conv3: [
    {
      id: 'm7', conversationId: 'conv3', contactId: 'c3', teamId: DEMO_TEAM_ID,
      direction: 'inbound', platform: 'messenger', content: 'Hola, vi sus productos en Instagram, me interesan.',
      messageType: 'text', status: 'read', isAiGenerated: false, createdAt: '2026-03-05T20:30:00Z',
    },
    {
      id: 'm8', conversationId: 'conv3', contactId: 'c3', teamId: DEMO_TEAM_ID,
      direction: 'outbound', platform: 'messenger', content: '¡Hola Ana! Sí, tenemos disponibilidad. ¿Cuál te interesa?',
      messageType: 'text', status: 'read', sentBy: 'agent1', isAiGenerated: false, createdAt: '2026-03-05T20:35:00Z',
    },
    {
      id: 'm9', conversationId: 'conv3', contactId: 'c3', teamId: DEMO_TEAM_ID,
      direction: 'inbound', platform: 'messenger', content: '¿Tienen envíos a Monterrey?',
      messageType: 'text', status: 'delivered', isAiGenerated: false, createdAt: '2026-03-05T20:45:00Z',
    },
  ],
};

export const demoOrders: Order[] = [
  {
    id: 'ord1', teamId: DEMO_TEAM_ID, contactId: 'c1', contact: demoContacts[0],
    conversationId: 'conv1', orderNumber: 'ORD-M1A2B3-XYZ',
    status: 'processing',
    items: [
      { id: 'i1', name: 'Crema Hidratante Premium', sku: 'SKU-001', quantity: 2, unitPrice: 350, total: 700 },
      { id: 'i2', name: 'Sérum Vitamina C', sku: 'SKU-015', quantity: 1, unitPrice: 480, total: 480 },
    ],
    subtotal: 1180, tax: 188.8, shipping: 99, total: 1467.80,
    shippingAddress: 'Av. Reforma 123, CDMX', notes: 'Empacar con cuidado, es regalo.',
    createdAt: '2026-03-05T16:00:00Z', updatedAt: '2026-03-06T09:00:00Z',
  },
  {
    id: 'ord2', teamId: DEMO_TEAM_ID, contactId: 'c5', contact: demoContacts[4],
    conversationId: 'conv5', orderNumber: 'ORD-N4C5D6-ABC',
    status: 'new',
    items: [
      { id: 'i3', name: 'Kit Básico Skincare', sku: 'SKU-050', quantity: 50, unitPrice: 200, total: 10000 },
    ],
    subtotal: 10000, tax: 1600, shipping: 0, total: 11600,
    shippingAddress: 'Blvd. Insurgentes 456, CDMX',
    notes: 'Pedido mayoreo. Requiere factura.',
    createdAt: '2026-03-06T10:30:00Z', updatedAt: '2026-03-06T10:30:00Z',
  },
  {
    id: 'ord3', teamId: DEMO_TEAM_ID, contactId: 'c2', contact: demoContacts[1],
    orderNumber: 'ORD-P7E8F9-DEF',
    status: 'shipped',
    items: [
      { id: 'i4', name: 'Protector Solar SPF50', sku: 'SKU-022', quantity: 1, unitPrice: 290, total: 290 },
    ],
    subtotal: 290, tax: 46.4, shipping: 99, total: 435.40,
    shippingAddress: 'Av. Vallarta 789, Guadalajara',
    trackingNumber: 'MX1234567890',
    notes: '', createdAt: '2026-03-02T11:00:00Z', updatedAt: '2026-03-05T15:00:00Z',
  },
  {
    id: 'ord4', teamId: DEMO_TEAM_ID, contactId: 'c3', contact: demoContacts[2],
    conversationId: 'conv3', orderNumber: 'ORD-Q1G2H3-GHI',
    status: 'confirmed',
    items: [
      { id: 'i5', name: 'Mascarilla Nocturna', sku: 'SKU-033', quantity: 3, unitPrice: 180, total: 540 },
      { id: 'i6', name: 'Tónico Facial', sku: 'SKU-011', quantity: 2, unitPrice: 220, total: 440 },
    ],
    subtotal: 980, tax: 156.8, shipping: 149, total: 1285.80,
    shippingAddress: 'Calle Morelos 321, Monterrey',
    notes: '', createdAt: '2026-03-04T14:00:00Z', updatedAt: '2026-03-05T08:00:00Z',
  },
  {
    id: 'ord5', teamId: DEMO_TEAM_ID, contactId: 'c1', contact: demoContacts[0],
    orderNumber: 'ORD-R4I5J6-JKL',
    status: 'delivered',
    items: [
      { id: 'i7', name: 'Set de Brochas', sku: 'SKU-100', quantity: 1, unitPrice: 650, total: 650 },
    ],
    subtotal: 650, tax: 104, shipping: 99, total: 853,
    shippingAddress: 'Av. Reforma 123, CDMX',
    trackingNumber: 'MX9876543210',
    notes: '', createdAt: '2026-02-20T10:00:00Z', updatedAt: '2026-02-25T14:00:00Z',
  },
  {
    id: 'ord6', teamId: DEMO_TEAM_ID, contactId: 'c4', contact: demoContacts[3],
    orderNumber: 'ORD-S7K8L9-MNO',
    status: 'packed',
    items: [
      { id: 'i8', name: 'Kit Influencer Deluxe', sku: 'SKU-200', quantity: 1, unitPrice: 1500, total: 1500 },
    ],
    subtotal: 1500, tax: 240, shipping: 0, total: 1740,
    shippingAddress: 'Polanco, CDMX',
    notes: 'Envío cortesía por colaboración.',
    createdAt: '2026-03-03T09:00:00Z', updatedAt: '2026-03-05T16:00:00Z',
  },
];

export const demoAIAgents: AIAgent[] = [
  {
    id: 'ai1', teamId: DEMO_TEAM_ID, name: 'Asistente de Ventas',
    providerId: 'openai-default',
    systemPrompt: 'Eres un asistente de ventas amigable para una tienda de skincare. Responde en español, sé conciso y ayuda a los clientes con información de productos, precios y proceso de compra. No inventes información sobre productos que no conozcas.',
    isActive: true, scope: 'all', selectedConversationIds: [],
    useBusinessHours: true, maxTokens: 500, temperature: 0.7,
    createdAt: '2026-02-01T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: 'ai2', teamId: DEMO_TEAM_ID, name: 'Soporte Post-venta',
    providerId: 'anthropic-default',
    systemPrompt: 'Eres un agente de soporte post-venta. Ayuda con seguimiento de pedidos, devoluciones y quejas. Sé empático y resolutivo. Responde siempre en español.',
    isActive: false, scope: 'selected', selectedConversationIds: ['conv1'],
    useBusinessHours: false, maxTokens: 800, temperature: 0.5,
    createdAt: '2026-02-15T10:00:00Z', updatedAt: '2026-03-01T10:00:00Z',
  },
];
